"""UniProt database helper tests."""

import pytest

from neurosnap.database.uniprot import fetch_accessions, fetch_uniprot


def test_fetch_uniprot_head_and_seq(monkeypatch):
  class Response:
    def __init__(self, status_code=200, text=""):
      self.status_code = status_code
      self.text = text

  monkeypatch.setattr("neurosnap.database.uniprot.requests.head", lambda url: Response(200))
  assert fetch_uniprot("P12345", head=True) is True

  fasta = ">sp|P12345| Some protein\nACDEFGHIKLMNPQRSTVWY\n"
  monkeypatch.setattr("neurosnap.database.uniprot.requests.get", lambda url: Response(200, fasta))
  monkeypatch.setattr("neurosnap.database.uniprot.read_msa", lambda text: iter([("h", "ACDEFGHIKLMNPQRSTVWY")]))
  assert fetch_uniprot("P12345", head=False) == "ACDEFGHIKLMNPQRSTVWY"

  def fake_get(url):
    if "uniprotkb" in url:
      return Response(404, "")
    return Response(200, fasta)

  monkeypatch.setattr("neurosnap.database.uniprot.requests.get", fake_get)
  sequence = fetch_uniprot("UPI000000", head=False)
  assert isinstance(sequence, str)


@pytest.mark.slow
@pytest.mark.integration
def test_fetch_accessions_live_uniprot():
  expected = {
    "P56704": "MAPLGYFLLLCSLKQALGSYPIWWSLAVGPQYSSLGSQPILCASIPGLVPKQLRFCRNYVEIMPSVAEGIKIGIQECQHQFRGRRWNCTTVHDSLAIFGPVLDKATRESAFVHAIASAGVAFAVTRSCAEGTAAICGCSSRHQGSPGKGWKWGGCSEDIEFGGMVSREFADARENRPDARSAMNRHNNEAGRQAIASHMHLKCKCHGLSGSCEVKTCWWSQPDFRAIGDFLKDKYDSASEMVVEKHRESRGWVETLRPRYTYFKVPTERDLVYYEASPNFCEPNPETGSFGTRDRTCNVSSHGIDGCDLLCCGRGHNARAERRREKCRCVFHWCCYVSCQECTRVYDVHTCK",
    "Q91029": "MRGPALLLALRALCALSALRGTARAVNNSGRWWGIINVASSTNLLTDSGSVQLVLEPGLQLLSRKQRRLIRQNPGILHSVSAGLQSAVRECQWQFRNRRWNCPTSQGPNIFGKIVNRGCRETAFIFAITSAGVTHSVARSCSEGSIESCTCDYRRRGPGGPDWHWGGCSDNIDFGRLFGREFVDSSEKGRDLRFLMNLHNNEAGRMTVFSEMRQECKCHGMSGSCTVRTCWMRLPTFRAVGDVLKDRFDGASRVIYGNKGSNRASRVELHHLEPENPAHKPPSPHDLVYFEKSPNFCTYSGKMGTAGTAGRACNSSSPGLDGCELLCCGRGFRTRTQRVTERCNCTFHWCCHVSCLNCTNTQVLHECL",
    "P27467": "MAPLGYLLVLCSLKQALGSYPIWWSLAVGPQYSSLSTQPILCASIPGLVPKQLRFCRNYVEIMPSVAEGVKAGIQECQHQFRGRRWNCTTVSNSLAIFGPVLDKATRESAFVHAIASAGVAFAVTRSCAEGSAAICGCSSRLQGSPGEGWKWGGCSEDIEFGGMVSREFADARENRPDARSAMNRHNNEAGRQAIASHMHLKCKCHGLSGSCEVKTCWWSQPDFRTIGDFLKDKYDSASEMVVEKHRESRGWVETLRPRYTYFKVPTERDLVYYEASPNFCEPNPETGSFGTRDRTCNVSSHGIDGCDLLCCGRGHNARTERRREKCHCVFHWCCYVSCQECTRVYDVHTCK",
    "O00755": "MNRKARRCLGHLFLSLGMVYLRIGGFSSVVALGASIICNKIPGLAPRQRAICQSRPDAIIVIGEGSQMGLDECQFQFRNGRWNCSALGERTVFGKELKVGSREAAFTYAIIAAGVAHAITAACTQGNLSDCGCDKEKQGQYHRDEGWKWGGCSADIRYGIGFAKVFVDAREIKQNARTLMNLHNNEAGRKILEENMKLECKCHGVSGSCTTKTCWTTLPQFRELGYVLKDKYNEAVHVEPVRASRNKRPTFLKIKKPLSYRKPMDTDLVYIEKSPNYCEEDPVTGSVGTQGRACNKTAPQASGCDLMCCGRGYNTHQYARVWQCNCKFHWCCYVKCNTCSERTEMYTCK",
    "Q2LMP1": "MASFGYFLFLCGLSQALSSYPIWWSLAIGHQYSSLGTQPILCGSIPGLVPKQLRFCRNYVEIMPSVAEGVKIGIQECQHQFRGRRWNCTTVNDSLAIFGPVLDKATRESAFVHAIASAGVAFAVTRSCAEGSATICGCDTRHKGSPGEGWKWGGCSEDVEFGSMVSREFADARENRPDARSAMNRHNNEAGRTSIIELMHLKCKCHGLSGSCEVKTCWWSQPDFRVIGDYLKDKYDSASEMVVEKHRESRGWVETLRPKYNFFKAPTEKDLVYYENSPNFCEPNPETGSFGTRDRICNVTSHGIDGCDLLCCGRGHNTRTEKRKEKCHCIFHWCCYVRCQECIRVYDVHTCK",
    "P28026": "MQNTTLFILATLLIFCPFFTASAWSVNNFLMTGPKAYLTYSASVAVGAQNGIEECKYQFAWERWNCPESTLQLATHNGLRSATRETSFVHAISSAGVMYTLTRNCSMGDFDNCGCDDSRNGRIGGRGWVWGGCSDNAEFGERISKLFVDGLETGQDARALMNLHNNEAGRLAVKETMKRTCKCHGISGSCSIQTCWLQLAEFRDIGNHLKIKHDQALKLEMDKRKMRSGNSADNRGAIADAFSSVAGSELIFLEDSPDYCLKNISLGLQGTEGRECLQSGKNLSQWERRSCKRLCTDCGLRVEEKKTEIISSCNCKFHWCCTVKCEQCKQVVIKHFCARRERDSNMLNTKRKNRGHRR",
  }

  actual = fetch_accessions(expected, batch_size=2)
  assert actual == expected
