"""Python-native topology and titration-state tables."""

# Generated from legacy vendored PDB2PQR data files.
# Keep values identical; only the on-disk representation has changed.

TOPOLOGY_DATA = [{'reference': {'name': 'ASP',
                'atoms': [{'name': 'N', 'bonds': ['CA', 'H'], 'altnames': [], 'x': 1.201, 'y': 0.847, 'z': 0.0},
                          {'name': 'CA', 'bonds': ['N', 'C', 'CB', 'HA'], 'altnames': [], 'x': 0.0, 'y': 0.0, 'z': 0.0},
                          {'name': 'C', 'bonds': ['CA', 'O'], 'altnames': [], 'x': -1.25, 'y': 0.881, 'z': 0.0},
                          {'name': 'O', 'bonds': ['C'], 'altnames': [], 'x': -2.185, 'y': 0.66, 'z': -0.784},
                          {'name': 'CB', 'bonds': ['CA', 'CG', 'HB2', 'HB3'], 'altnames': [], 'x': 0.043, 'y': -1.017, 'z': 1.123},
                          {'name': 'CG', 'bonds': ['CB', 'OD1', 'OD2'], 'altnames': [], 'x': 1.229, 'y': -1.966, 'z': 1.053},
                          {'name': 'OD1', 'bonds': ['CG'], 'altnames': [], 'x': 2.058, 'y': -1.864, 'z': 0.127},
                          {'name': 'OD2', 'bonds': ['CG'], 'altnames': [], 'x': 1.319, 'y': -2.81, 'z': 1.959},
                          {'name': 'H', 'bonds': ['N'], 'altnames': ['HN'], 'x': 1.201, 'y': 1.847, 'z': 0.0},
                          {'name': 'HA', 'bonds': ['CA'], 'altnames': [], 'x': 0.0, 'y': -0.511, 'z': -0.86},
                          {'name': 'HB2', 'bonds': ['CB'], 'altnames': ['2HB'], 'x': 0.086, 'y': -0.524, 'z': 1.992},
                          {'name': 'HB3', 'bonds': ['CB'], 'altnames': ['1HB', 'HB1', '3HB'], 'x': -0.796, 'y': -1.559, 'z': 1.089}],
                'dihedrals': ['N CA CB CG', 'CA CB CG OD1']},
  'titration_states': [{'name': 'ASP', 'tautomers': [{'name': 'ASP', 'conformers': [{'name': 'ASP', 'add': None, 'remove': None}]}]},
                       {'name': 'ASH',
                        'tautomers': [{'name': 'ASH1',
                                       'conformers': [{'name': 'ASH1c',
                                                       'add': {'atoms': [{'name': 'HD1',
                                                                          'bonds': ['OD1'],
                                                                          'altnames': ['1HD'],
                                                                          'x': 2.85,
                                                                          'y': -2.463,
                                                                          'z': 0.072}],
                                                               'dihedrals': ['CB CG OD1 HD1']},
                                                       'remove': None},
                                                      {'name': 'ASH1t',
                                                       'add': {'atoms': [{'name': 'HD1',
                                                                          'bonds': ['OD1'],
                                                                          'altnames': ['1HD'],
                                                                          'x': 1.955,
                                                                          'y': -1.18,
                                                                          'z': -0.588}],
                                                               'dihedrals': ['CB CG OD1 HD1']},
                                                       'remove': None}]},
                                      {'name': 'ASH2',
                                       'conformers': [{'name': 'ASH2c',
                                                       'add': {'atoms': [{'name': 'HD2',
                                                                          'bonds': ['OD2'],
                                                                          'altnames': ['2HD'],
                                                                          'x': 2.105,
                                                                          'y': -3.427,
                                                                          'z': 1.93}],
                                                               'dihedrals': ['CB CG OD2 HD2']},
                                                       'remove': None},
                                                      {'name': 'ASH2t',
                                                       'add': {'atoms': [{'name': 'HD2',
                                                                          'bonds': ['OD2'],
                                                                          'altnames': ['2HD'],
                                                                          'x': 0.599,
                                                                          'y': -2.812,
                                                                          'z': 2.652}],
                                                               'dihedrals': ['CB CG OD2 HD2']},
                                                       'remove': None}]}]}]},
 {'reference': {'name': 'GLU',
                'atoms': [{'name': 'N', 'bonds': ['CA', 'H'], 'altnames': [], 'x': 1.201, 'y': 0.847, 'z': 0.0},
                          {'name': 'CA', 'bonds': ['N', 'C', 'CB', 'HA'], 'altnames': [], 'x': 0.0, 'y': 0.0, 'z': 0.0},
                          {'name': 'C', 'bonds': ['CA', 'O'], 'altnames': [], 'x': -1.25, 'y': 0.881, 'z': 0.0},
                          {'name': 'O', 'bonds': ['C'], 'altnames': [], 'x': -2.185, 'y': 0.66, 'z': -0.784},
                          {'name': 'CB', 'bonds': ['CA', 'CG', 'HB2', 'HB3'], 'altnames': [], 'x': -0.059, 'y': -0.875, 'z': 1.258},
                          {'name': 'CG', 'bonds': ['CB', 'CD', 'HG2', 'HG3'], 'altnames': [], 'x': 1.082, 'y': -1.85, 'z': 1.501},
                          {'name': 'CD', 'bonds': ['CG', 'OE1', 'OE2'], 'altnames': [], 'x': 0.99, 'y': -2.687, 'z': 2.74},
                          {'name': 'OE1', 'bonds': ['CD'], 'altnames': [], 'x': 0.067, 'y': -2.624, 'z': 3.539},
                          {'name': 'OE2', 'bonds': ['CD'], 'altnames': [], 'x': 1.97, 'y': -3.449, 'z': 2.871},
                          {'name': 'H', 'bonds': ['N'], 'altnames': ['HN'], 'x': 1.201, 'y': 1.847, 'z': 0.0},
                          {'name': 'HA', 'bonds': ['CA'], 'altnames': [], 'x': 0.0, 'y': -0.582, 'z': -0.813},
                          {'name': 'HB2', 'bonds': ['CB'], 'altnames': ['2HB'], 'x': -0.099, 'y': -0.26, 'z': 2.046},
                          {'name': 'HB3', 'bonds': ['CB'], 'altnames': ['1HB', 'HB1', '3HB'], 'x': -0.903, 'y': -1.409, 'z': 1.21},
                          {'name': 'HG2', 'bonds': ['CG'], 'altnames': ['2HG'], 'x': 1.124, 'y': -2.469, 'z': 0.717},
                          {'name': 'HG3', 'bonds': ['CG'], 'altnames': ['1HG', 'HG1', '3HG'], 'x': 1.929, 'y': -1.321, 'z': 1.553}],
                'dihedrals': ['N CA CB CG', 'CA CB CG CD', 'CB CG CD OE1']},
  'titration_states': [{'name': 'GLU', 'tautomers': [{'name': 'GLU', 'conformers': [{'name': 'GLU', 'add': None, 'remove': None}]}]},
                       {'name': 'GLH',
                        'tautomers': [{'name': 'GLH1',
                                       'conformers': [{'name': 'GLH1c',
                                                       'add': {'atoms': [{'name': 'HE1',
                                                                          'bonds': ['OE1'],
                                                                          'altnames': ['1HE'],
                                                                          'x': 0.036,
                                                                          'y': -3.194,
                                                                          'z': 4.361}],
                                                               'dihedrals': ['CG CD OE1 HE1']},
                                                       'remove': None},
                                                      {'name': 'GLH1t',
                                                       'add': {'atoms': [{'name': 'HE1',
                                                                          'bonds': ['OE1'],
                                                                          'altnames': ['1HE'],
                                                                          'x': -0.704,
                                                                          'y': -1.999,
                                                                          'z': 3.412}],
                                                               'dihedrals': ['CG CD OE1 HE1']},
                                                       'remove': None}]},
                                      {'name': 'GLH2',
                                       'conformers': [{'name': 'GLH2c',
                                                       'add': {'atoms': [{'name': 'HE2',
                                                                          'bonds': ['OE2'],
                                                                          'altnames': ['2HE'],
                                                                          'x': 1.977,
                                                                          'y': -4.036,
                                                                          'z': 3.68}],
                                                               'dihedrals': ['CG CD OE2 HE2']},
                                                       'remove': None},
                                                      {'name': 'GLH2t',
                                                       'add': {'atoms': [{'name': 'HE2',
                                                                          'bonds': ['OE2'],
                                                                          'altnames': ['2HE'],
                                                                          'x': 2.668,
                                                                          'y': -3.41,
                                                                          'z': 2.156}],
                                                               'dihedrals': ['CG CD OE2 HE2']},
                                                       'remove': None}]}]}]},
 {'reference': {'name': 'ARG',
                'atoms': [{'name': 'N', 'bonds': ['CA', 'H'], 'altnames': [], 'x': 1.201, 'y': 0.847, 'z': 0.0},
                          {'name': 'CA', 'bonds': ['N', 'C', 'CB', 'HA'], 'altnames': [], 'x': 0.0, 'y': 0.0, 'z': 0.0},
                          {'name': 'C', 'bonds': ['CA', 'O'], 'altnames': [], 'x': -1.25, 'y': 0.881, 'z': 0.0},
                          {'name': 'O', 'bonds': ['C'], 'altnames': [], 'x': -2.185, 'y': 0.66, 'z': -0.784},
                          {'name': 'CB', 'bonds': ['CA', 'CG', 'HB2', 'HB3'], 'altnames': [], 'x': -0.019, 'y': -0.932, 'z': 1.222},
                          {'name': 'CG', 'bonds': ['CB', 'CD', 'HG2', 'HG3'], 'altnames': [], 'x': 1.158, 'y': -1.892, 'z': 1.324},
                          {'name': 'CD', 'bonds': ['CG', 'NE', 'HD2', 'HD3'], 'altnames': [], 'x': 1.06, 'y': -2.755, 'z': 2.534},
                          {'name': 'NE', 'bonds': ['CD', 'CZ', 'HE'], 'altnames': [], 'x': 2.184, 'y': -3.677, 'z': 2.638},
                          {'name': 'CZ', 'bonds': ['NE', 'NH1', 'NH2'], 'altnames': [], 'x': 2.321, 'y': -4.549, 'z': 3.631},
                          {'name': 'NH1', 'bonds': ['CZ', 'HH11', 'HH12'], 'altnames': [], 'x': 1.541, 'y': -4.507, 'z': 4.705},
                          {'name': 'NH2', 'bonds': ['CZ', 'HH21', 'HH22'], 'altnames': [], 'x': 3.296, 'y': -5.454, 'z': 3.573},
                          {'name': 'H', 'bonds': ['N'], 'altnames': ['HN'], 'x': 1.201, 'y': 1.847, 'z': 0.0},
                          {'name': 'HA', 'bonds': ['CA'], 'altnames': [], 'x': 0.0, 'y': -0.558, 'z': -0.83},
                          {'name': 'HB2', 'bonds': ['CB'], 'altnames': ['2HB'], 'x': -0.027, 'y': -0.363, 'z': 2.044},
                          {'name': 'HB3', 'bonds': ['CB'], 'altnames': ['1HB', 'HB1', '3HB'], 'x': -0.858, 'y': -1.474, 'z': 1.184},
                          {'name': 'HG2', 'bonds': ['CG'], 'altnames': ['2HG'], 'x': 1.174, 'y': -2.473, 'z': 0.51},
                          {'name': 'HG3', 'bonds': ['CG'], 'altnames': ['1HG', 'HG1', '3HG'], 'x': 2.005, 'y': -1.362, 'z': 1.371},
                          {'name': 'HD2', 'bonds': ['CD'], 'altnames': ['2HD'], 'x': 1.044, 'y': -2.172, 'z': 3.346},
                          {'name': 'HD3', 'bonds': ['CD'], 'altnames': ['1HD', 'HD1', '3HD'], 'x': 0.212, 'y': -3.283, 'z': 2.485},
                          {'name': 'HE', 'bonds': ['NE'], 'altnames': [], 'x': 2.887, 'y': -3.652, 'z': 1.927},
                          {'name': 'HH11', 'bonds': ['NH1'], 'altnames': ['1HH1'], 'x': 0.817, 'y': -3.82, 'z': 4.771},
                          {'name': 'HH12', 'bonds': ['NH1'], 'altnames': ['2HH1'], 'x': 1.676, 'y': -5.163, 'z': 5.448},
                          {'name': 'HH21', 'bonds': ['NH2'], 'altnames': ['1HH2'], 'x': 3.903, 'y': -5.485, 'z': 2.779},
                          {'name': 'HH22', 'bonds': ['NH2'], 'altnames': ['2HH2'], 'x': 3.42, 'y': -6.103, 'z': 4.323}],
                'dihedrals': ['N CA CB CG', 'CA CB CG CD', 'CB CG CD NE', 'CG CD NE CZ', 'CD NE CZ NH1']},
  'titration_states': [{'name': 'ARG', 'tautomers': [{'name': 'ARG', 'conformers': [{'name': 'ARG', 'add': None, 'remove': None}]}]},
                       {'name': 'AR0', 'tautomers': []}]},
 {'reference': {'name': 'HIS',
                'atoms': [{'name': 'N', 'bonds': ['CA', 'H'], 'altnames': [], 'x': 1.201, 'y': 0.847, 'z': 0.0},
                          {'name': 'CA', 'bonds': ['N', 'C', 'CB', 'HA'], 'altnames': [], 'x': 0.0, 'y': 0.0, 'z': 0.0},
                          {'name': 'C', 'bonds': ['CA', 'O'], 'altnames': [], 'x': -1.25, 'y': 0.881, 'z': 0.0},
                          {'name': 'O', 'bonds': ['C'], 'altnames': [], 'x': -2.185, 'y': 0.66, 'z': -0.784},
                          {'name': 'CB', 'bonds': ['CA', 'CG', 'HB2', 'HB3'], 'altnames': [], 'x': -0.062, 'y': -0.963, 'z': 1.211},
                          {'name': 'CG', 'bonds': ['CB', 'ND1', 'CD2'], 'altnames': [], 'x': 1.102, 'y': -1.908, 'z': 1.266},
                          {'name': 'ND1', 'bonds': ['CG', 'CE1', 'HD1'], 'altnames': [], 'x': 2.279, 'y': -1.643, 'z': 1.921},
                          {'name': 'CD2', 'bonds': ['CG', 'NE2', 'HD2'], 'altnames': [], 'x': 1.195, 'y': -3.189, 'z': 0.838},
                          {'name': 'CE1', 'bonds': ['ND1', 'NE2', 'HE1'], 'altnames': [], 'x': 3.044, 'y': -2.718, 'z': 1.891},
                          {'name': 'NE2', 'bonds': ['CD2', 'CE1', 'HE2'], 'altnames': [], 'x': 2.411, 'y': -3.674, 'z': 1.242},
                          {'name': 'H', 'bonds': ['N'], 'altnames': ['HN'], 'x': 1.201, 'y': 1.847, 'z': 0.0},
                          {'name': 'HA', 'bonds': ['CA'], 'altnames': [], 'x': 0.0, 'y': -0.547, 'z': -0.837},
                          {'name': 'HB2', 'bonds': ['CB'], 'altnames': ['2HB'], 'x': -0.073, 'y': -0.42, 'z': 2.051},
                          {'name': 'HB3', 'bonds': ['CB'], 'altnames': ['1HB', 'HB1', '3HB'], 'x': -0.905, 'y': -1.498, 'z': 1.15},
                          {'name': 'HD1', 'bonds': ['ND1'], 'altnames': [], 'x': 2.518, 'y': -0.773, 'z': 2.353},
                          {'name': 'HD2', 'bonds': ['CD2'], 'altnames': [], 'x': 0.502, 'y': -3.69, 'z': 0.32},
                          {'name': 'HE1', 'bonds': ['CE1'], 'altnames': [], 'x': 3.956, 'y': -2.794, 'z': 2.294},
                          {'name': 'HE2', 'bonds': ['NE2'], 'altnames': [], 'x': 2.758, 'y': -4.596, 'z': 1.074}],
                'dihedrals': ['N CA CB CG', 'CA CB CG ND1']},
  'titration_states': [{'name': 'HIS',
                        'tautomers': [{'name': 'HSD',
                                       'conformers': [{'name': 'HSD1',
                                                       'add': None,
                                                       'remove': {'atoms': [{'name': 'HE2', 'bonds': [], 'altnames': []}],
                                                                  'dihedrals': []}},
                                                      {'name': 'HSD2',
                                                       'add': {'atoms': [{'name': 'ND1',
                                                                          'bonds': ['CG', 'CE1', 'HD1'],
                                                                          'altnames': [],
                                                                          'x': 1.12,
                                                                          'y': -3.143,
                                                                          'z': 0.667},
                                                                         {'name': 'CD2',
                                                                          'bonds': ['CG', 'NE2', 'HD2'],
                                                                          'altnames': [],
                                                                          'x': 2.349,
                                                                          'y': -1.715,
                                                                          'z': 1.757},
                                                                         {'name': 'CE1',
                                                                          'bonds': ['ND1', 'NE2', 'HE1'],
                                                                          'altnames': [],
                                                                          'x': 2.325,
                                                                          'y': -3.668,
                                                                          'z': 0.791},
                                                                         {'name': 'NE2',
                                                                          'bonds': ['CD2', 'CE1', 'HE2'],
                                                                          'altnames': [],
                                                                          'x': 3.093,
                                                                          'y': -2.822,
                                                                          'z': 1.446},
                                                                         {'name': 'HD1',
                                                                          'bonds': ['ND1'],
                                                                          'altnames': [],
                                                                          'x': 0.343,
                                                                          'y': -3.577,
                                                                          'z': 0.21},
                                                                         {'name': 'HD2',
                                                                          'bonds': ['CD2'],
                                                                          'altnames': [],
                                                                          'x': 2.668,
                                                                          'y': -0.91,
                                                                          'z': 2.258},
                                                                         {'name': 'HE1',
                                                                          'bonds': ['CE1'],
                                                                          'altnames': [],
                                                                          'x': 2.608,
                                                                          'y': -4.562,
                                                                          'z': 0.444}],
                                                               'dihedrals': []},
                                                       'remove': {'atoms': [{'name': 'ND1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'CD2', 'bonds': [], 'altnames': []},
                                                                            {'name': 'CE1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'NE2', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HD1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HD2', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HE1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HE2', 'bonds': [], 'altnames': []}],
                                                                  'dihedrals': []}}]},
                                      {'name': 'HSE',
                                       'conformers': [{'name': 'HSE1',
                                                       'add': None,
                                                       'remove': {'atoms': [{'name': 'HD1', 'bonds': [], 'altnames': []}],
                                                                  'dihedrals': []}},
                                                      {'name': 'HSE2',
                                                       'add': {'atoms': [{'name': 'ND1',
                                                                          'bonds': ['CG', 'CE1', 'HD1'],
                                                                          'altnames': [],
                                                                          'x': 1.12,
                                                                          'y': -3.143,
                                                                          'z': 0.667},
                                                                         {'name': 'CD2',
                                                                          'bonds': ['CG', 'NE2', 'HD2'],
                                                                          'altnames': [],
                                                                          'x': 2.349,
                                                                          'y': -1.715,
                                                                          'z': 1.757},
                                                                         {'name': 'CE1',
                                                                          'bonds': ['ND1', 'NE2', 'HE1'],
                                                                          'altnames': [],
                                                                          'x': 2.325,
                                                                          'y': -3.668,
                                                                          'z': 0.791},
                                                                         {'name': 'NE2',
                                                                          'bonds': ['CD2', 'CE1', 'HE2'],
                                                                          'altnames': [],
                                                                          'x': 3.093,
                                                                          'y': -2.822,
                                                                          'z': 1.446},
                                                                         {'name': 'HD2',
                                                                          'bonds': ['CD2'],
                                                                          'altnames': [],
                                                                          'x': 2.668,
                                                                          'y': -0.91,
                                                                          'z': 2.258},
                                                                         {'name': 'HE1',
                                                                          'bonds': ['CE1'],
                                                                          'altnames': [],
                                                                          'x': 2.608,
                                                                          'y': -4.562,
                                                                          'z': 0.444},
                                                                         {'name': 'HE2',
                                                                          'bonds': ['NE2'],
                                                                          'altnames': [],
                                                                          'x': 4.056,
                                                                          'y': -2.962,
                                                                          'z': 1.676}],
                                                               'dihedrals': []},
                                                       'remove': {'atoms': [{'name': 'ND1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'CD2', 'bonds': [], 'altnames': []},
                                                                            {'name': 'CE1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'NE2', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HD1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HD2', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HE1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HE2', 'bonds': [], 'altnames': []}],
                                                                  'dihedrals': []}}]}]},
                       {'name': 'HSP',
                        'tautomers': [{'name': 'HSP',
                                       'conformers': [{'name': 'HSP1', 'add': None, 'remove': None},
                                                      {'name': 'HSP2',
                                                       'add': {'atoms': [{'name': 'ND1',
                                                                          'bonds': ['CG', 'CE1', 'HD1'],
                                                                          'altnames': [],
                                                                          'x': 1.12,
                                                                          'y': -3.143,
                                                                          'z': 0.667},
                                                                         {'name': 'CD2',
                                                                          'bonds': ['CG', 'NE2', 'HD2'],
                                                                          'altnames': [],
                                                                          'x': 2.349,
                                                                          'y': -1.715,
                                                                          'z': 1.757},
                                                                         {'name': 'CE1',
                                                                          'bonds': ['ND1', 'NE2', 'HE1'],
                                                                          'altnames': [],
                                                                          'x': 2.325,
                                                                          'y': -3.668,
                                                                          'z': 0.791},
                                                                         {'name': 'NE2',
                                                                          'bonds': ['CD2', 'CE1', 'HE2'],
                                                                          'altnames': [],
                                                                          'x': 3.093,
                                                                          'y': -2.822,
                                                                          'z': 1.446},
                                                                         {'name': 'HD1',
                                                                          'bonds': ['ND1'],
                                                                          'altnames': [],
                                                                          'x': 0.343,
                                                                          'y': -3.577,
                                                                          'z': 0.21},
                                                                         {'name': 'HD2',
                                                                          'bonds': ['CD2'],
                                                                          'altnames': [],
                                                                          'x': 2.668,
                                                                          'y': -0.91,
                                                                          'z': 2.258},
                                                                         {'name': 'HE1',
                                                                          'bonds': ['CE1'],
                                                                          'altnames': [],
                                                                          'x': 2.608,
                                                                          'y': -4.562,
                                                                          'z': 0.444},
                                                                         {'name': 'HE2',
                                                                          'bonds': ['NE2'],
                                                                          'altnames': [],
                                                                          'x': 4.056,
                                                                          'y': -2.962,
                                                                          'z': 1.676}],
                                                               'dihedrals': []},
                                                       'remove': {'atoms': [{'name': 'ND1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'CD2', 'bonds': [], 'altnames': []},
                                                                            {'name': 'CE1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'NE2', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HD1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HD2', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HE1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HE2', 'bonds': [], 'altnames': []}],
                                                                  'dihedrals': []}}]}]},
                       {'name': 'HIS-',
                        'tautomers': [{'name': 'HIS-',
                                       'conformers': [{'name': 'HIS-1',
                                                       'add': None,
                                                       'remove': {'atoms': [{'name': 'HD1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HE2', 'bonds': [], 'altnames': []}],
                                                                  'dihedrals': []}},
                                                      {'name': 'HIS-2',
                                                       'add': {'atoms': [{'name': 'ND1',
                                                                          'bonds': ['CG', 'CE1', 'HD1'],
                                                                          'altnames': [],
                                                                          'x': 1.12,
                                                                          'y': -3.143,
                                                                          'z': 0.667},
                                                                         {'name': 'CD2',
                                                                          'bonds': ['CG', 'NE2', 'HD2'],
                                                                          'altnames': [],
                                                                          'x': 2.349,
                                                                          'y': -1.715,
                                                                          'z': 1.757},
                                                                         {'name': 'CE1',
                                                                          'bonds': ['ND1', 'NE2', 'HE1'],
                                                                          'altnames': [],
                                                                          'x': 2.325,
                                                                          'y': -3.668,
                                                                          'z': 0.791},
                                                                         {'name': 'NE2',
                                                                          'bonds': ['CD2', 'CE1', 'HE2'],
                                                                          'altnames': [],
                                                                          'x': 3.093,
                                                                          'y': -2.822,
                                                                          'z': 1.446},
                                                                         {'name': 'HD2',
                                                                          'bonds': ['CD2'],
                                                                          'altnames': [],
                                                                          'x': 2.668,
                                                                          'y': -0.91,
                                                                          'z': 2.258},
                                                                         {'name': 'HE1',
                                                                          'bonds': ['CE1'],
                                                                          'altnames': [],
                                                                          'x': 2.608,
                                                                          'y': -4.562,
                                                                          'z': 0.444}],
                                                               'dihedrals': []},
                                                       'remove': {'atoms': [{'name': 'ND1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'CD2', 'bonds': [], 'altnames': []},
                                                                            {'name': 'CE1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'NE2', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HD1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HD2', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HE1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HE2', 'bonds': [], 'altnames': []}],
                                                                  'dihedrals': []}}]}]}]},
 {'reference': {'name': 'NTER', 'atoms': [], 'dihedrals': []},
  'titration_states': [{'name': 'NTER',
                        'tautomers': [{'name': 'NTER',
                                       'conformers': [{'name': 'NTER',
                                                       'add': {'atoms': [{'name': 'H',
                                                                          'bonds': ['N'],
                                                                          'altnames': ['HT1', 'H1', '1H'],
                                                                          'x': 0.934,
                                                                          'y': 1.811,
                                                                          'z': 0.0},
                                                                         {'name': 'H2',
                                                                          'bonds': ['N'],
                                                                          'altnames': ['HT2', '2H'],
                                                                          'x': 1.746,
                                                                          'y': 0.653,
                                                                          'z': -0.817},
                                                                         {'name': 'H3',
                                                                          'bonds': ['N'],
                                                                          'altnames': ['HT3', '3H'],
                                                                          'x': 1.746,
                                                                          'y': 0.653,
                                                                          'z': 0.817},
                                                                         {'name': 'N+1',
                                                                          'bonds': ['C'],
                                                                          'altnames': [],
                                                                          'x': -1.252,
                                                                          'y': 1.877,
                                                                          'z': 1.023}],
                                                               'dihedrals': []},
                                                       'remove': None}]}]},
                       {'name': 'NTER0',
                        'tautomers': [{'name': 'NTER0',
                                       'conformers': [{'name': 'NTER0',
                                                       'add': {'atoms': [{'name': 'H',
                                                                          'bonds': ['N'],
                                                                          'altnames': ['HT1', 'H1', '1H'],
                                                                          'x': 0.934,
                                                                          'y': 1.811,
                                                                          'z': 0.0},
                                                                         {'name': 'H2',
                                                                          'bonds': ['N'],
                                                                          'altnames': ['HT2', '2H'],
                                                                          'x': 1.746,
                                                                          'y': 0.653,
                                                                          'z': -0.817},
                                                                         {'name': 'N+1',
                                                                          'bonds': ['C'],
                                                                          'altnames': [],
                                                                          'x': -1.252,
                                                                          'y': 1.877,
                                                                          'z': 1.023}],
                                                               'dihedrals': []},
                                                       'remove': {'atoms': [{'name': 'H3', 'bonds': [], 'altnames': []}],
                                                                  'dihedrals': []}}]}]}]},
 {'reference': {'name': 'CTER', 'atoms': [], 'dihedrals': []},
  'titration_states': [{'name': 'CTER',
                        'tautomers': [{'name': 'CTER',
                                       'conformers': [{'name': 'CTER',
                                                       'add': {'atoms': [{'name': 'OXT',
                                                                          'bonds': ['C'],
                                                                          'altnames': ["O''", 'OT2'],
                                                                          'x': -1.529,
                                                                          'y': 1.858,
                                                                          'z': 0.695},
                                                                         {'name': 'O',
                                                                          'bonds': ['C'],
                                                                          'altnames': ["O'", 'OT1'],
                                                                          'x': -2.185,
                                                                          'y': 0.66,
                                                                          'z': -0.784},
                                                                         {'name': 'C-1',
                                                                          'bonds': ['N'],
                                                                          'altnames': [],
                                                                          'x': 2.339,
                                                                          'y': 0.216,
                                                                          'z': 0.0}],
                                                               'dihedrals': []},
                                                       'remove': None}]}]},
                       {'name': 'CTER0',
                        'tautomers': [{'name': 'CTER01',
                                       'conformers': [{'name': 'CTER01c',
                                                       'add': {'atoms': [{'name': 'HO',
                                                                          'bonds': ['O'],
                                                                          'altnames': [],
                                                                          'x': -2.998,
                                                                          'y': 1.241,
                                                                          'z': -0.768},
                                                                         {'name': 'OXT',
                                                                          'bonds': ['C'],
                                                                          'altnames': ["O''", 'OT2'],
                                                                          'x': -1.529,
                                                                          'y': 1.858,
                                                                          'z': 0.695},
                                                                         {'name': 'O',
                                                                          'bonds': ['C'],
                                                                          'altnames': ["O'", 'OT1'],
                                                                          'x': -2.185,
                                                                          'y': 0.66,
                                                                          'z': -0.784},
                                                                         {'name': 'C-1',
                                                                          'bonds': ['N'],
                                                                          'altnames': [],
                                                                          'x': 2.339,
                                                                          'y': 0.216,
                                                                          'z': 0.0}],
                                                               'dihedrals': []},
                                                       'remove': None},
                                                      {'name': 'CTER01t',
                                                       'add': {'atoms': [{'name': 'HO',
                                                                          'bonds': ['O'],
                                                                          'altnames': [],
                                                                          'x': -2.125,
                                                                          'y': -0.099,
                                                                          'z': -1.431},
                                                                         {'name': 'OXT',
                                                                          'bonds': ['C'],
                                                                          'altnames': ["O''", 'OT2'],
                                                                          'x': -1.529,
                                                                          'y': 1.858,
                                                                          'z': 0.695},
                                                                         {'name': 'O',
                                                                          'bonds': ['C'],
                                                                          'altnames': ["O'", 'OT1'],
                                                                          'x': -2.185,
                                                                          'y': 0.66,
                                                                          'z': -0.784},
                                                                         {'name': 'C-1',
                                                                          'bonds': ['N'],
                                                                          'altnames': [],
                                                                          'x': 2.339,
                                                                          'y': 0.216,
                                                                          'z': 0.0}],
                                                               'dihedrals': []},
                                                       'remove': None}]},
                                      {'name': 'CTER02',
                                       'conformers': [{'name': 'CTER02c',
                                                       'add': {'atoms': [{'name': 'HO',
                                                                          'bonds': ['OXT'],
                                                                          'altnames': [],
                                                                          'x': -2.401,
                                                                          'y': 2.33,
                                                                          'z': 0.567},
                                                                         {'name': 'OXT',
                                                                          'bonds': ['C'],
                                                                          'altnames': ["O''", 'OT2'],
                                                                          'x': -1.529,
                                                                          'y': 1.858,
                                                                          'z': 0.695},
                                                                         {'name': 'O',
                                                                          'bonds': ['C'],
                                                                          'altnames': ["O'", 'OT1'],
                                                                          'x': -2.185,
                                                                          'y': 0.66,
                                                                          'z': -0.784},
                                                                         {'name': 'C-1',
                                                                          'bonds': ['N'],
                                                                          'altnames': [],
                                                                          'x': 2.339,
                                                                          'y': 0.216,
                                                                          'z': 0.0}],
                                                               'dihedrals': []},
                                                       'remove': None},
                                                      {'name': 'CTER02t',
                                                       'add': {'atoms': [{'name': 'HO',
                                                                          'bonds': ['OXT'],
                                                                          'altnames': [],
                                                                          'x': -0.883,
                                                                          'y': 2.18,
                                                                          'z': 1.387},
                                                                         {'name': 'OXT',
                                                                          'bonds': ['C'],
                                                                          'altnames': ["O''", 'OT2'],
                                                                          'x': -1.529,
                                                                          'y': 1.858,
                                                                          'z': 0.695},
                                                                         {'name': 'O',
                                                                          'bonds': ['C'],
                                                                          'altnames': ["O'", 'OT1'],
                                                                          'x': -2.185,
                                                                          'y': 0.66,
                                                                          'z': -0.784},
                                                                         {'name': 'C-1',
                                                                          'bonds': ['N'],
                                                                          'altnames': [],
                                                                          'x': 2.339,
                                                                          'y': 0.216,
                                                                          'z': 0.0}],
                                                               'dihedrals': []},
                                                       'remove': None}]}]}]},
 {'reference': {'name': 'ASN',
                'atoms': [{'name': 'N', 'bonds': ['CA', 'H'], 'altnames': [], 'x': 1.201, 'y': 0.847, 'z': 0.0},
                          {'name': 'CA', 'bonds': ['N', 'C', 'CB', 'HA'], 'altnames': [], 'x': 0.0, 'y': 0.0, 'z': 0.0},
                          {'name': 'C', 'bonds': ['CA', 'O'], 'altnames': [], 'x': -1.25, 'y': 0.881, 'z': 0.0},
                          {'name': 'O', 'bonds': ['C'], 'altnames': [], 'x': -2.185, 'y': 0.66, 'z': -0.784},
                          {'name': 'CB', 'bonds': ['CA', 'CG', 'HB2', 'HB3'], 'altnames': [], 'x': 0.05, 'y': -1.025, 'z': 1.129},
                          {'name': 'CG', 'bonds': ['CB', 'OD1', 'ND2'], 'altnames': [], 'x': 1.239, 'y': -1.965, 'z': 1.044},
                          {'name': 'OD1', 'bonds': ['CG'], 'altnames': [], 'x': 2.06, 'y': -1.867, 'z': 0.126},
                          {'name': 'ND2', 'bonds': ['CG', 'HD21', 'HD22'], 'altnames': [], 'x': 1.344, 'y': -2.87, 'z': 2.015},
                          {'name': 'H', 'bonds': ['N'], 'altnames': ['HN'], 'x': 1.201, 'y': 1.847, 'z': 0.0},
                          {'name': 'HA', 'bonds': ['CA'], 'altnames': [], 'x': 0.0, 'y': -0.51, 'z': -0.86},
                          {'name': 'HB2', 'bonds': ['CB'], 'altnames': ['2HB'], 'x': 0.096, 'y': -0.535, 'z': 2.0},
                          {'name': 'HB3', 'bonds': ['CB'], 'altnames': ['1HB', 'HB1', '3HB'], 'x': -0.788, 'y': -1.571, 'z': 1.098},
                          {'name': 'HD22', 'bonds': ['ND2'], 'altnames': ['2HD2'], 'x': 0.657, 'y': -2.905, 'z': 2.741},
                          {'name': 'HD21', 'bonds': ['ND2'], 'altnames': ['1HD2'], 'x': 2.108, 'y': -3.514, 'z': 2.018}],
                'dihedrals': ['N CA CB CG', 'CA CB CG OD1']},
  'titration_states': [{'name': 'ASN',
                        'tautomers': [{'name': 'ASN',
                                       'conformers': [{'name': 'ASN1', 'add': None, 'remove': None},
                                                      {'name': 'ASN2',
                                                       'add': {'atoms': [{'name': 'OD1',
                                                                          'bonds': ['CG'],
                                                                          'altnames': [],
                                                                          'x': 1.411,
                                                                          'y': -2.848,
                                                                          'z': 1.891},
                                                                         {'name': 'ND2',
                                                                          'bonds': ['CG', 'HD21', 'HD22'],
                                                                          'altnames': [],
                                                                          'x': 2.055,
                                                                          'y': -1.789,
                                                                          'z': 0.007},
                                                                         {'name': 'HD22',
                                                                          'bonds': ['ND2'],
                                                                          'altnames': ['2HD2'],
                                                                          'x': 1.87,
                                                                          'y': -1.064,
                                                                          'z': -0.656},
                                                                         {'name': 'HD21',
                                                                          'bonds': ['ND2'],
                                                                          'altnames': ['1HD2'],
                                                                          'x': 2.845,
                                                                          'y': -2.373,
                                                                          'z': -0.197}],
                                                               'dihedrals': []},
                                                       'remove': {'atoms': [{'name': 'OD1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'ND2', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HD21', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HD22', 'bonds': [], 'altnames': []}],
                                                                  'dihedrals': []}}]}]},
                       {'name': 'ASN+', 'tautomers': []}]},
 {'reference': {'name': 'GLN',
                'atoms': [{'name': 'N', 'bonds': ['CA', 'H'], 'altnames': [], 'x': 1.201, 'y': 0.847, 'z': 0.0},
                          {'name': 'CA', 'bonds': ['N', 'C', 'CB', 'HA'], 'altnames': [], 'x': 0.0, 'y': 0.0, 'z': 0.0},
                          {'name': 'C', 'bonds': ['CA', 'O'], 'altnames': [], 'x': -1.25, 'y': 0.881, 'z': 0.0},
                          {'name': 'O', 'bonds': ['C'], 'altnames': [], 'x': -2.185, 'y': 0.66, 'z': -0.784},
                          {'name': 'CB', 'bonds': ['CA', 'CG', 'HB2', 'HB3'], 'altnames': [], 'x': -0.018, 'y': -0.986, 'z': 1.179},
                          {'name': 'CG', 'bonds': ['CB', 'CD', 'HG2', 'HG3'], 'altnames': [], 'x': 1.159, 'y': -1.939, 'z': 1.188},
                          {'name': 'CD', 'bonds': ['CG', 'OE1', 'NE2'], 'altnames': [], 'x': 1.117, 'y': -2.896, 'z': 2.354},
                          {'name': 'OE1', 'bonds': ['CD'], 'altnames': [], 'x': 0.214, 'y': -2.882, 'z': 3.191},
                          {'name': 'NE2', 'bonds': ['CD', 'HE21', 'HE22'], 'altnames': [], 'x': 2.144, 'y': -3.752, 'z': 2.427},
                          {'name': 'H', 'bonds': ['N'], 'altnames': ['HN'], 'x': 1.201, 'y': 1.847, 'z': 0.0},
                          {'name': 'HA', 'bonds': ['CA'], 'altnames': [], 'x': 0.0, 'y': -0.533, 'z': -0.846},
                          {'name': 'HB2', 'bonds': ['CB'], 'altnames': ['2HB'], 'x': -0.007, 'y': -0.462, 'z': 2.03},
                          {'name': 'HB3', 'bonds': ['CB'], 'altnames': ['1HB', 'HB1', '3HB'], 'x': -0.86, 'y': -1.524, 'z': 1.129},
                          {'name': 'HG2', 'bonds': ['CG'], 'altnames': ['2HG'], 'x': 1.151, 'y': -2.468, 'z': 0.339},
                          {'name': 'HG3', 'bonds': ['CG'], 'altnames': ['1HG', 'HG1', '3HG'], 'x': 2.004, 'y': -1.406, 'z': 1.24},
                          {'name': 'HE21', 'bonds': ['NE2'], 'altnames': ['1HE2'], 'x': 2.198, 'y': -4.425, 'z': 3.196},
                          {'name': 'HE22', 'bonds': ['NE2'], 'altnames': ['2HE2'], 'x': 2.86, 'y': -3.722, 'z': 1.713}],
                'dihedrals': ['N CA CB CG', 'CA CB CG CD', 'CB CG CD OE1']},
  'titration_states': [{'name': 'GLN',
                        'tautomers': [{'name': 'GLN',
                                       'conformers': [{'name': 'GLN1', 'add': None, 'remove': None},
                                                      {'name': 'GLN2',
                                                       'add': {'atoms': [{'name': 'OE1',
                                                                          'bonds': ['CD'],
                                                                          'altnames': [],
                                                                          'x': 1.983,
                                                                          'y': -3.751,
                                                                          'z': 2.542},
                                                                         {'name': 'NE2',
                                                                          'bonds': ['CD', 'HE21', 'HE22'],
                                                                          'altnames': [],
                                                                          'x': 0.058,
                                                                          'y': -2.764,
                                                                          'z': 3.163},
                                                                         {'name': 'HE21',
                                                                          'bonds': ['NE2'],
                                                                          'altnames': ['1HE2'],
                                                                          'x': -0.053,
                                                                          'y': -3.384,
                                                                          'z': 3.969},
                                                                         {'name': 'HE22',
                                                                          'bonds': ['NE2'],
                                                                          'altnames': ['2HE2'],
                                                                          'x': -0.625,
                                                                          'y': -2.045,
                                                                          'z': 2.964}],
                                                               'dihedrals': []},
                                                       'remove': {'atoms': [{'name': 'OE1', 'bonds': [], 'altnames': []},
                                                                            {'name': 'NE2', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HE21', 'bonds': [], 'altnames': []},
                                                                            {'name': 'HE22', 'bonds': [], 'altnames': []}],
                                                                  'dihedrals': []}}]}]},
                       {'name': 'GLN+', 'tautomers': []}]},
 {'reference': {'name': 'LYS',
                'atoms': [{'name': 'N', 'bonds': ['CA', 'H'], 'altnames': [], 'x': 1.201, 'y': 0.847, 'z': 0.0},
                          {'name': 'CA', 'bonds': ['N', 'C', 'CB', 'HA'], 'altnames': [], 'x': 0.0, 'y': 0.0, 'z': 0.0},
                          {'name': 'C', 'bonds': ['CA', 'O'], 'altnames': [], 'x': -1.25, 'y': 0.881, 'z': 0.0},
                          {'name': 'O', 'bonds': ['C'], 'altnames': [], 'x': -2.185, 'y': 0.66, 'z': -0.784},
                          {'name': 'CB', 'bonds': ['CA', 'CG', 'HB2', 'HB3'], 'altnames': [], 'x': -0.03, 'y': -0.922, 'z': 1.219},
                          {'name': 'CG', 'bonds': ['CB', 'CD', 'HG2', 'HG3'], 'altnames': [], 'x': 1.154, 'y': -1.877, 'z': 1.315},
                          {'name': 'CD', 'bonds': ['CG', 'CE', 'HD2', 'HD3'], 'altnames': [], 'x': 1.06, 'y': -2.763, 'z': 2.546},
                          {'name': 'CE', 'bonds': ['CD', 'NZ', 'HE2', 'HE3'], 'altnames': [], 'x': 2.224, 'y': -3.719, 'z': 2.663},
                          {'name': 'NZ', 'bonds': ['CE', 'HZ1', 'HZ2', 'HZ3'], 'altnames': [], 'x': 2.09, 'y': -4.562, 'z': 3.878},
                          {'name': 'H', 'bonds': ['N'], 'altnames': ['HN'], 'x': 1.201, 'y': 1.847, 'z': 0.0},
                          {'name': 'HA', 'bonds': ['CA'], 'altnames': [], 'x': 0.0, 'y': -0.56, 'z': -0.829},
                          {'name': 'HB2', 'bonds': ['CB'], 'altnames': ['2HB'], 'x': -0.04, 'y': -0.354, 'z': 2.041},
                          {'name': 'HB3', 'bonds': ['CB'], 'altnames': ['1HB', 'HB1', '3HB'], 'x': -0.868, 'y': -1.466, 'z': 1.179},
                          {'name': 'HG2', 'bonds': ['CG'], 'altnames': ['2HG'], 'x': 1.171, 'y': -2.456, 'z': 0.499},
                          {'name': 'HG3', 'bonds': ['CG'], 'altnames': ['1HG', 'HG1', '3HG'], 'x': 1.999, 'y': -1.344, 'z': 1.362},
                          {'name': 'HD2', 'bonds': ['CD'], 'altnames': ['2HD'], 'x': 1.04, 'y': -2.18, 'z': 3.359},
                          {'name': 'HD3', 'bonds': ['CD'], 'altnames': ['1HD', 'HD1', '3HD'], 'x': 0.213, 'y': -3.293, 'z': 2.496},
                          {'name': 'HE2', 'bonds': ['CE'], 'altnames': ['2HE'], 'x': 2.248, 'y': -4.308, 'z': 1.855},
                          {'name': 'HE3', 'bonds': ['CE'], 'altnames': ['1HE', 'HE1', '3HE'], 'x': 3.075, 'y': -3.196, 'z': 2.718},
                          {'name': 'HZ1', 'bonds': ['NZ'], 'altnames': ['1HZ'], 'x': 2.07, 'y': -3.977, 'z': 4.689},
                          {'name': 'HZ2', 'bonds': ['NZ'], 'altnames': ['2HZ'], 'x': 1.242, 'y': -5.089, 'z': 3.826},
                          {'name': 'HZ3', 'bonds': ['NZ'], 'altnames': ['3HZ'], 'x': 2.868, 'y': -5.187, 'z': 3.938}],
                'dihedrals': ['N CA CB CG', 'CA CB CG CD', 'CB CG CD CE', 'CG CD CE NZ', 'CD CE NZ HZ1']},
  'titration_states': [{'name': 'LYS', 'tautomers': [{'name': 'LYS', 'conformers': [{'name': 'LYS', 'add': None, 'remove': None}]}]},
                       {'name': 'LYS0',
                        'tautomers': [{'name': 'LYS0',
                                       'conformers': [{'name': 'LYS0',
                                                       'add': None,
                                                       'remove': {'atoms': [{'name': 'HZ3', 'bonds': [], 'altnames': []}],
                                                                  'dihedrals': []}}]}]}]},
 {'reference': {'name': 'SER',
                'atoms': [{'name': 'N', 'bonds': ['CA', 'H'], 'altnames': [], 'x': 1.201, 'y': 0.847, 'z': 0.0},
                          {'name': 'CA', 'bonds': ['N', 'C', 'CB', 'HA'], 'altnames': [], 'x': 0.0, 'y': 0.0, 'z': 0.0},
                          {'name': 'C', 'bonds': ['CA', 'O'], 'altnames': [], 'x': -1.25, 'y': 0.881, 'z': 0.0},
                          {'name': 'O', 'bonds': ['C'], 'altnames': [], 'x': -2.185, 'y': 0.66, 'z': -0.784},
                          {'name': 'CB', 'bonds': ['CA', 'OG', 'HB2', 'HB3'], 'altnames': [], 'x': 0.014, 'y': -0.971, 'z': 1.174},
                          {'name': 'OG', 'bonds': ['CB', 'HG'], 'altnames': [], 'x': 0.056, 'y': -0.296, 'z': 2.418},
                          {'name': 'H', 'bonds': ['N'], 'altnames': ['HN'], 'x': 1.201, 'y': 1.847, 'z': 0.0},
                          {'name': 'HA', 'bonds': ['CA'], 'altnames': [], 'x': 0.0, 'y': -0.536, 'z': -0.844},
                          {'name': 'HB2', 'bonds': ['CB'], 'altnames': ['2HB'], 'x': -0.812, 'y': -1.533, 'z': 1.139},
                          {'name': 'HB3', 'bonds': ['CB'], 'altnames': ['1HB', 'HB1', '3HB'], 'x': 0.82, 'y': -1.558, 'z': 1.098},
                          {'name': 'HG', 'bonds': ['OG'], 'altnames': [], 'x': 0.067, 'y': 0.691, 'z': 2.262}],
                'dihedrals': ['N CA CB OG', 'CA CB OG HG']},
  'titration_states': [{'name': 'SER', 'tautomers': [{'name': 'SER', 'conformers': [{'name': 'SER', 'add': None, 'remove': None}]}]},
                       {'name': 'SER-',
                        'tautomers': [{'name': 'SER-',
                                       'conformers': [{'name': 'SER-',
                                                       'add': None,
                                                       'remove': {'atoms': [{'name': 'HG', 'bonds': [], 'altnames': []}],
                                                                  'dihedrals': []}}]}]}]},
 {'reference': {'name': 'THR',
                'atoms': [{'name': 'N', 'bonds': ['CA', 'H'], 'altnames': [], 'x': 1.201, 'y': 0.847, 'z': 0.0},
                          {'name': 'CA', 'bonds': ['N', 'C', 'CB', 'HA'], 'altnames': [], 'x': 0.0, 'y': 0.0, 'z': 0.0},
                          {'name': 'C', 'bonds': ['CA', 'O'], 'altnames': [], 'x': -1.25, 'y': 0.881, 'z': 0.0},
                          {'name': 'O', 'bonds': ['C'], 'altnames': [], 'x': -2.185, 'y': 0.66, 'z': -0.784},
                          {'name': 'CB', 'bonds': ['CA', 'OG1', 'CG2', 'HB'], 'altnames': [], 'x': 0.001, 'y': -0.981, 'z': 1.242},
                          {'name': 'OG1', 'bonds': ['CB', 'HG1'], 'altnames': [], 'x': 1.226, 'y': -1.775, 'z': 1.136},
                          {'name': 'CG2', 'bonds': ['CB', 'HG21', 'HG22', 'HG23'], 'altnames': [], 'x': -1.252, 'y': -1.866, 'z': 1.324},
                          {'name': 'H', 'bonds': ['N'], 'altnames': ['HN'], 'x': 1.201, 'y': 1.847, 'z': 0.0},
                          {'name': 'HA', 'bonds': ['CA'], 'altnames': [], 'x': 0.0, 'y': -0.549, 'z': -0.836},
                          {'name': 'HB', 'bonds': ['CB'], 'altnames': [], 'x': 0.054, 'y': -0.432, 'z': 2.076},
                          {'name': 'HG1', 'bonds': ['OG1'], 'altnames': ['1HG'], 'x': 1.735, 'y': -1.497, 'z': 0.321},
                          {'name': 'HG21', 'bonds': ['CG2'], 'altnames': ['1HG2'], 'x': -2.064, 'y': -1.287, 'z': 1.399},
                          {'name': 'HG22', 'bonds': ['CG2'], 'altnames': ['2HG2'], 'x': -1.318, 'y': -2.427, 'z': 0.498},
                          {'name': 'HG23', 'bonds': ['CG2'], 'altnames': ['3HG2'], 'x': -1.19, 'y': -2.459, 'z': 2.126}],
                'dihedrals': ['N CA CB OG1', 'CA CB OG1 HG1']},
  'titration_states': [{'name': 'THR', 'tautomers': [{'name': 'THR', 'conformers': [{'name': 'THR', 'add': None, 'remove': None}]}]},
                       {'name': 'THR-',
                        'tautomers': [{'name': 'THR-',
                                       'conformers': [{'name': 'THR-',
                                                       'add': None,
                                                       'remove': {'atoms': [{'name': 'HG1', 'bonds': [], 'altnames': []}],
                                                                  'dihedrals': []}}]}]}]},
 {'reference': {'name': 'TYR',
                'atoms': [{'name': 'N', 'bonds': ['CA', 'H'], 'altnames': [], 'x': 1.201, 'y': 0.847, 'z': 0.0},
                          {'name': 'CA', 'bonds': ['N', 'C', 'CB', 'HA'], 'altnames': [], 'x': 0.0, 'y': 0.0, 'z': 0.0},
                          {'name': 'C', 'bonds': ['CA', 'O'], 'altnames': [], 'x': -1.25, 'y': 0.881, 'z': 0.0},
                          {'name': 'O', 'bonds': ['C'], 'altnames': [], 'x': -2.185, 'y': 0.66, 'z': -0.784},
                          {'name': 'CB', 'bonds': ['CA', 'CG', 'HB2', 'HB3'], 'altnames': [], 'x': 0.012, 'y': -0.963, 'z': 1.196},
                          {'name': 'CG', 'bonds': ['CB', 'CD1', 'CD2'], 'altnames': [], 'x': 1.193, 'y': -1.914, 'z': 1.235},
                          {'name': 'CD1', 'bonds': ['CG', 'CE1', 'HD1'], 'altnames': [], 'x': 2.381, 'y': -1.57, 'z': 1.891},
                          {'name': 'CD2', 'bonds': ['CG', 'CE2', 'HD2'], 'altnames': [], 'x': 1.136, 'y': -3.152, 'z': 0.597},
                          {'name': 'CE1', 'bonds': ['CD1', 'CZ', 'HE1'], 'altnames': [], 'x': 3.48, 'y': -2.427, 'z': 1.889},
                          {'name': 'CE2', 'bonds': ['CD2', 'CZ', 'HE2'], 'altnames': [], 'x': 2.228, 'y': -4.012, 'z': 0.583},
                          {'name': 'CZ', 'bonds': ['CE1', 'CE2', 'OH'], 'altnames': [], 'x': 3.404, 'y': -3.644, 'z': 1.219},
                          {'name': 'OH', 'bonds': ['CZ', 'HH'], 'altnames': [], 'x': 4.469, 'y': -4.494, 'z': 1.141},
                          {'name': 'H', 'bonds': ['N'], 'altnames': ['HN'], 'x': 1.201, 'y': 1.847, 'z': 0.0},
                          {'name': 'HA', 'bonds': ['CA'], 'altnames': [], 'x': 0.0, 'y': -0.543, 'z': -0.84},
                          {'name': 'HB2', 'bonds': ['CB'], 'altnames': ['2HB'], 'x': 0.023, 'y': -0.418, 'z': 2.034},
                          {'name': 'HB3', 'bonds': ['CB'], 'altnames': ['1HB', 'HB1', '3HB'], 'x': -0.825, 'y': -1.509, 'z': 1.164},
                          {'name': 'HD1', 'bonds': ['CD1'], 'altnames': ['1HD'], 'x': 2.443, 'y': -0.694, 'z': 2.369},
                          {'name': 'HD2', 'bonds': ['CD2'], 'altnames': ['2HD'], 'x': 0.29, 'y': -3.428, 'z': 0.14},
                          {'name': 'HE1', 'bonds': ['CE1'], 'altnames': ['1HE'], 'x': 4.319, 'y': -2.169, 'z': 2.368},
                          {'name': 'HE2', 'bonds': ['CE2'], 'altnames': ['2HE'], 'x': 2.166, 'y': -4.894, 'z': 0.115},
                          {'name': 'HH', 'bonds': ['OH'], 'altnames': [], 'x': 4.215, 'y': -5.298, 'z': 0.603}],
                'dihedrals': ['N CA CB CG', 'CA CB CG CD1', 'CE2 CZ OH HH']},
  'titration_states': [{'name': 'TYR', 'tautomers': [{'name': 'TYR', 'conformers': [{'name': 'TYR', 'add': None, 'remove': None}]}]},
                       {'name': 'TYR-',
                        'tautomers': [{'name': 'TYR-',
                                       'conformers': [{'name': 'TYR-',
                                                       'add': None,
                                                       'remove': {'atoms': [{'name': 'HH', 'bonds': [], 'altnames': []}],
                                                                  'dihedrals': []}}]}]}]},
 {'reference': {'name': 'CYS',
                'atoms': [{'name': 'N', 'bonds': ['CA', 'H'], 'altnames': [], 'x': 1.201, 'y': 0.847, 'z': 0.0},
                          {'name': 'CA', 'bonds': ['N', 'C', 'CB', 'HA'], 'altnames': [], 'x': 0.0, 'y': 0.0, 'z': 0.0},
                          {'name': 'C', 'bonds': ['CA', 'O'], 'altnames': [], 'x': -1.25, 'y': 0.881, 'z': 0.0},
                          {'name': 'O', 'bonds': ['C'], 'altnames': [], 'x': -2.185, 'y': 0.66, 'z': -0.784},
                          {'name': 'CB', 'bonds': ['CA', 'SG', 'HB2', 'HB3'], 'altnames': [], 'x': 0.018, 'y': -0.958, 'z': 1.184},
                          {'name': 'SG', 'bonds': ['CB', 'HG'], 'altnames': [], 'x': 1.431, 'y': -2.085, 'z': 1.212},
                          {'name': 'H', 'bonds': ['N'], 'altnames': ['HN'], 'x': 1.201, 'y': 1.847, 'z': 0.0},
                          {'name': 'HA', 'bonds': ['CA'], 'altnames': [], 'x': 0.0, 'y': -0.542, 'z': -0.84},
                          {'name': 'HB2', 'bonds': ['CB'], 'altnames': ['2HB'], 'x': 0.033, 'y': -0.417, 'z': 2.024},
                          {'name': 'HB3', 'bonds': ['CB'], 'altnames': ['1HB', 'HB1', '3HB'], 'x': -0.818, 'y': -1.506, 'z': 1.155},
                          {'name': 'HG', 'bonds': ['SG'], 'altnames': ['1HG', 'HG1'], 'x': 2.014, 'y': -1.908, 'z': 0.419}],
                'dihedrals': ['N CA CB SG']},
  'titration_states': [{'name': 'CYS', 'tautomers': [{'name': 'CYS', 'conformers': [{'name': 'CYS', 'add': None, 'remove': None}]}]},
                       {'name': 'CYS-',
                        'tautomers': [{'name': 'CYS-',
                                       'conformers': [{'name': 'CYS-',
                                                       'add': None,
                                                       'remove': {'atoms': [{'name': 'HG', 'bonds': [], 'altnames': []}],
                                                                  'dihedrals': []}}]}]}]}]
