"""Minimal vendored PDB2PQR IO helpers used by the Neurosnap adapter."""

from __future__ import annotations

import io
import logging
from collections import Counter

from . import definitions as defns
from . import pdb
from .config import (
  FILTER_WARNINGS,
  FILTER_WARNINGS_LIMIT,
)

_LOGGER = logging.getLogger(__name__)


class DuplicateFilter(logging.Filter):
  """Filter duplicate warning messages from the vendored PDB2PQR engine."""

  def __init__(self):
    super().__init__()
    self.warn_count = Counter()

  def filter(self, record):
    if record.levelname == "WARNING":
      for prefix in FILTER_WARNINGS:
        if record.getMessage().startswith(prefix):
          self.warn_count.update([prefix])
          if self.warn_count[prefix] > FILTER_WARNINGS_LIMIT:
            return False
          if self.warn_count[prefix] == FILTER_WARNINGS_LIMIT:
            _LOGGER.warning('Suppressing further "%s" messages', prefix)
            return False
          return True
    return True


def print_biomolecule_atoms(atomlist, chainflag: bool = False, pdbfile: bool = False):
  """Return PDB or PQR text lines for vendored atom objects."""
  text = []
  current_chain_id = None
  for atom_index, atom in enumerate(atomlist):
    if current_chain_id is None:
      current_chain_id = atom.chain_id
    elif atom.chain_id != current_chain_id:
      current_chain_id = atom.chain_id
      text.append("TER\n")
    atom.serial = atom_index + 1
    if pdbfile:
      text.append(f"{atom.get_pdb_string()}\n")
    else:
      text.append(f"{atom.get_pqr_string(chainflag=chainflag)}\n")
  text.append("TER\nEND\n")
  return text


def get_old_header(pdblist) -> str:
  """Return the original PDB header text from vendored parsed records."""
  old_header = io.StringIO()
  header_types = (
    pdb.HEADER,
    pdb.TITLE,
    pdb.COMPND,
    pdb.SOURCE,
    pdb.KEYWDS,
    pdb.EXPDTA,
    pdb.AUTHOR,
    pdb.REVDAT,
    pdb.JRNL,
    pdb.REMARK,
    pdb.SPRSDE,
    pdb.NUMMDL,
  )
  for pdb_obj in pdblist:
    if not isinstance(pdb_obj, header_types):
      break
    old_header.write(str(pdb_obj))
    old_header.write("\n")
  return old_header.getvalue()


def print_pqr_header(
  pdblist,
  atomlist,
  reslist,
  charge,
  force_field,
  ph_calc_method,
  ph,
  ffout,
  include_old_header: bool = False,
) -> str:
  """Generate a Neurosnap-appropriate PQR header."""
  if force_field is None:
    force_field = "User force field"
  else:
    force_field = force_field.upper()

  lines = [
    "REMARK   1 PQR file generated by Neurosnap",
    "REMARK   1",
    f"REMARK   1 Forcefield Used: {force_field}",
  ]
  if ffout is not None:
    lines.append(f"REMARK   1 Naming Scheme Used: {ffout.upper()}")
  lines.append("REMARK   1")

  if ph_calc_method is not None:
    lines.extend(
      [
        f"REMARK   1 pKas calculated by {ph_calc_method} and assigned using pH {ph:.2f}",
        "REMARK   1",
      ]
    )

  if atomlist:
    lines.extend(
      [
        "REMARK   5 WARNING: PDB2PQR was unable to assign charges",
        "REMARK   5 to the following atoms (omitted below):",
      ]
    )
    for atom in atomlist:
      lines.append(f"REMARK   5    {atom.serial} {atom.name} in {atom.residue.name} {atom.residue.res_seq}")
    lines.extend(
      [
        "REMARK   5 This is usually due to the fact that this residue is not",
        "REMARK   5 an amino acid or nucleic acid; or, there are no parameters",
        "REMARK   5 available for the specific protonation state of this",
        "REMARK   5 residue in the selected forcefield.",
        "REMARK   5",
      ]
    )

  if reslist:
    lines.extend(
      [
        "REMARK   5 WARNING: Non-integral net charges were found in",
        "REMARK   5 the following residues:",
      ]
    )
    for residue in reslist:
      lines.append(f"REMARK   5    {residue} - Residue Charge: {residue.charge:.4f}")
    lines.append("REMARK   5")

  lines.extend(
    [
      f"REMARK   6 Total charge on this biomolecule: {charge:.4f} e",
      "REMARK   6",
    ]
  )

  if include_old_header:
    lines.extend(["REMARK   7 Original PDB header follows", "REMARK   7"])
    old_header = get_old_header(pdblist).rstrip()
    if old_header:
      lines.append(old_header)

  return "\n".join(lines) + "\n"
def get_definitions():
  """Load vendored topology definitions from Python-native data tables."""
  return defns.Definition()
