"""Domain-organized constants used throughout Neurosnap."""

from .api import USER_AGENT
from .chemistry import ATOMIC_MASSES, VDW_RADII_BONDI, VDW_RADII_UFF
from .sequence import AA_ALIASES, AA_MASS_FREE, AA_MASS_PROTEIN_AVG, AA_MASS_PROTEIN_MONO, AA_RECORDS, DEFAULT_PKA, STANDARD_AAs, AARecord
from .structure import BACKBONE_ATOMS_AA, BACKBONE_ATOMS_DNA, BACKBONE_ATOMS_RNA, HYDROPHOBIC_RESIDUES, NUC_DNA_CODES, NUC_RNA_CODES, STANDARD_NUCLEOTIDES

__all__ = [
  "AARecord",
  "AA_ALIASES",
  "AA_MASS_FREE",
  "AA_MASS_PROTEIN_AVG",
  "AA_MASS_PROTEIN_MONO",
  "AA_RECORDS",
  "ATOMIC_MASSES",
  "BACKBONE_ATOMS_AA",
  "BACKBONE_ATOMS_DNA",
  "BACKBONE_ATOMS_RNA",
  "DEFAULT_PKA",
  "HYDROPHOBIC_RESIDUES",
  "NUC_DNA_CODES",
  "NUC_RNA_CODES",
  "STANDARD_AAs",
  "STANDARD_NUCLEOTIDES",
  "USER_AGENT",
  "VDW_RADII_BONDI",
  "VDW_RADII_UFF",
]
