#!/usr/bin/env python3
"""Patch autogenerated Sphinx apidoc titles to use Neurosnap SDK naming."""

from pathlib import Path


def replace_once(text: str, old: str, new: str) -> str:
  return text.replace(old, new, 1) if old in text else text


def patch_file(path: Path, replacements: list[tuple[str, str]]) -> None:
  content = path.read_text(encoding="utf-8")
  original = content
  for old, new in replacements:
    content = replace_once(content, old, new)
  if content != original:
    path.write_text(content, encoding="utf-8")


def main() -> None:
  repo_root = Path(__file__).resolve().parents[1]
  docs_source = repo_root / "docs/source"

  patch_file(
    docs_source / "modules.rst",
    [
      ("neurosnap\n=========\n", "Neurosnap SDK\n=============\n"),
    ],
  )

  patch_file(
    docs_source / "neurosnap.rst",
    [
      ("neurosnap package\n=================\n", "Neurosnap SDK package\n=====================\n"),
    ],
  )


if __name__ == "__main__":
  main()
